# Generated by Django 2.2.13 on 2022-05-05 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220504_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_studying',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_img',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
